<?php

return [

	/*
    * Resident profile name extensions
    */
	'name_extensions' => [
		'N/A',
		'Jr.',
		'Sr.',
		'I',
		'II',
		'III',
	],

	'prefix'  => [
		'Mr.',
		'Ms.',
		'Mrs.',
		'Sir',
		'Maam',
		'Engr.',
		'Atty.',
		'Dr.',
		'Dra.',
	],

	'gender' => [
		'Female',
		'Male',
	],

	'bloodtype' => [
		'Not yet verified',
		'A+',
		'A-',
		'B+',
		'B-',
		'O+',
		'O-',
		'AB+',
		'AB-',
	],

	'physical_status' => [
		'N/A',
		'Person With Disability',
	],

	'employment_status' => [
		'Self Employed',
		'Employed',
		'Unemployed',
		'Student',
		'Out of School Youth',
		'Retired',
	],

	'marital_status' => [
		'Single',
		'Single Parent',
		'Married',
		'Widow',
		'Legally Separated',
		'Annulled',
		'Divorce',
	],


  /* User Management */

    'users_role' => [
        'LGU',
        // 'Manager',
        // 'Administrator',
        // 'Encoder',
    ],


    /*
    * Pumpboat profile
    */
    'safety_equipment' => [
        'Life Jacket',
        'Life Buoy',
        'Buoyant Heaving Line',
        'Bailer or Hand Pump',
        'Sound-signalling Devices',
        'Navigation Lights',
        'Fire Extinguisher',
        'Waterproof Flashlight',
        'First Aid Kit',
    ],

    'hull_material' => [
        'Organic materials not including wood or plywood',
        'Wood and/or plywood, with or without paint',
        'Wood and/or plywood, with no other composites, with metal or resin or other plastic coating or cladding',
        'Composites, including fiberglass and wood or plywood coated with composites',
        'Flexible (generally, inflatable) material, including rubber, vinyl, hypalon and the like',
        'Concrete',
        'Molded plastic',
        'Aluminum',
        'Steel',
        'Other',
    ],

    'amenities' => [
        'Seating',
        'Shade',
        'Life Jackets',
        'Handrails',
        'Steps or Ladders',
        'Storage Spaces or Compartments',
        'Toilet Facilities',
        'Snorkeling and Fishing Gear',
        'Refreshments',
        'Sound System',
        'Lighting System',
    ],

		'countries' => [
			'Afghanistan',
			'Albania',
			'Algeria',
			'Andorra',
			'Angola',
			'Antigua and Barbuda',
			'Argentina',
			'Armenia',
			'Australia',
			'Austria',
			'Azerbaijan',
			'The Bahamas',
			'Bahrain',
			'Bangladesh',
			'Barbados',
			'Belarus',
			'Belgium',
			'Belize',
			'Benin',
			'Bhutan',
			'Bolivia',
			'Bosnia and Herzegovina',
			'Botswana',
			'Brazil',
			'Brunei',
			'Bulgaria',
			'Burkina Faso',
			'Burundi',
			'Cabo Verde',
			'Cambodia',
			'Cameroon',
			'Canada',
			'Central African Republic',
			'Chad',
			'Chile',
			'China',
			'Colombia',
			'Comoros',
			'Congo, Democratic Republic of the',
			'Congo, Republic of the',
			'Costa Rica',
			'Côte d’Ivoire',
			'Croatia',
			'Cuba',
			'Cyprus',
			'Czech Republic',
			'Denmark',
			'Djibouti',
			'Dominica',
			'Dominican Republic',
			'East Timor (Timor-Leste)',
			'Ecuador',
			'Egypt',
			'El Salvador',
			'Equatorial Guinea',
			'Eritrea',
			'Estonia',
			'Eswatini',
			'Ethiopia',
			'Fiji',
			'Finland',
			'France',
			'Gabon',
			'The Gambia',
			'Georgia',
			'Germany',
			'Ghana',
			'Greece',
			'Grenada',
			'Guatemala',
			'Guinea',
			'Guinea-Bissau',
			'Guyana',
			'Haiti',
			'Honduras',
			'Hungary',
			'Iceland',
			'India',
			'Indonesia',
			'Iran',
			'Iraq',
			'Ireland',
			'Israel',
			'Italy',
			'Jamaica',
			'Japan',
			'Jordan',
			'Kazakhstan',
			'Kenya',
			'Kiribati',
			'Korea, North',
			'Korea, South',
			'Kosovo',
			'Kuwait',
			'Kyrgyzstan',
			'Laos',
			'Latvia',
			'Lebanon',
			'Lesotho',
			'Liberia',
			'Libya',
			'Liechtenstein',
			'Lithuania',
			'Luxembourg',
			'Madagascar',
			'Malawi',
			'Malaysia',
			'Maldives',
			'Mali',
			'Malta',
			'Marshall Islands',
			'Mauritania',
			'Mauritius',
			'Mexico',
			'Micronesia, Federated States of',
			'Moldova',
			'Monaco',
			'Mongolia',
			'Montenegro',
			'Morocco',
			'Mozambique',
			'Myanmar (Burma)',
			'Namibia',
			'Nauru',
			'Nepal',
			'Netherlands',
			'New Zealand',
			'Nicaragua',
			'Niger',
			'Nigeria',
			'North Macedonia',
			'Norway',
			'Oman',
			'Pakistan',
			'Palau',
			'Panama',
			'Papua New Guinea',
			'Paraguay',
			'Peru',
			'Philippines',
			'Poland',
			'Portugal',
			'Qatar',
			'Romania',
			'Russia',
			'Rwanda',
			'Saint Kitts and Nevis',
			'Saint Lucia',
			'Saint Vincent and the Grenadines',
			'Samoa',
			'San Marino',
			'Sao Tome and Principe',
			'Saudi Arabia',
			'Senegal',
			'Serbia',
			'Seychelles',
			'Sierra Leone',
			'Singapore',
			'Slovakia',
			'Slovenia',
			'Solomon Islands',
			'Somalia',
			'South Africa',
			'Spain',
			'Sri Lanka',
			'Sudan',
			'Sudan, South',
			'Suriname',
			'Sweden',
			'Switzerland',
			'Syria',
			'Taiwan',
			'Tajikistan',
			'Tanzania',
			'Thailand',
			'Togo',
			'Tonga',
			'Trinidad and Tobago',
			'Tunisia',
			'Turkey',
			'Turkmenistan',
			'Tuvalu',
			'Uganda',
			'Ukraine',
			'United Arab Emirates',
			'United Kingdom',
			'United States',
			'Uruguay',
			'Uzbekistan',
			'Vanuatu',
			'Vatican City',
			'Venezuela',
			'Vietnam',
			'Yemen',
			'Zambia',
			'Zimbabwe',
		],












];
